#!/bin/sh

if [ $# -lt 2 ]
then
  echo "usage: version platforms+" 1>&2
  exit 1
fi

VERSION="$1"
shift
PLATFORMS="$@"

cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<project
  xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <!--                                                                 -->
  <!-- Auto generated by jogl-main.pom.sh, do not edit directly! -->
  <!--                                                                 -->

  <modelVersion>4.0.0</modelVersion>
  <groupId>org.jogamp.jogl</groupId>
  <artifactId>jogl-main</artifactId>
  <version>${VERSION}</version>
  <packaging>jar</packaging>
  <name>JOGL atomics</name>
  <description>Java™ Binding for the OpenGL® API (Atomics frontend)</description>
  <url>http://jogamp.org/jogl/www/</url>

  <!--                                                                   -->
  <!-- Explicitly depend on jogl, and all of its native binary jars. -->
  <!--                                                                   -->

  <dependencies>
    <dependency>
      <groupId>\${project.groupId}</groupId>
      <artifactId>jogl</artifactId>
      <version>\${project.version}</version>
    </dependency>

EOF

for BACKEND in osx win x11
do
  cat <<EOF
    <dependency>
      <groupId>\${project.groupId}</groupId>
      <artifactId>jogl</artifactId>
      <version>\${project.version}</version>
      <classifier>os-${BACKEND}</classifier>
    </dependency>
EOF
done

echo

for PLATFORM in ${PLATFORMS}
do
  cat <<EOF
    <dependency>
      <groupId>\${project.groupId}</groupId>
      <artifactId>jogl</artifactId>
      <version>\${project.version}</version>
      <classifier>natives-${PLATFORM}</classifier>
    </dependency>
EOF
done

cat <<EOF
  </dependencies>

EOF

cat ../jogl/pom.in || exit 1
cat <<EOF
</project>
EOF
