#! /bin/bash
### BEGIN INIT INFO
# Provides:          jabot
# Required-Start:    $local_fs $remote_fs $network $syslog $time
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Should-Start:      apache2
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: IRC JABot init script
# Description:       Init script for jabot services
### END INIT INFO

#
# jabot    Start/Stop the IRC JABot
#
# chkconfig: 345 91 10
# description: IRC JABot. \
# processname: jabot


# Source function library.
. /lib/lsb/init-functions

# Check that networking is up.
# [ "${NETWORKING}" = "no" ] && exit 0

JABOT_USER=jabot
JABOT_HOME=/srv/$JABOT_USER/jabot
startup=$JABOT_HOME/scripts/start.jabot-jogamp.sh
shutdown=$JABOT_HOME/scripts/stop.jabot.sh

start(){
 echo -n $"Starting Jabot service: "
 su - $JABOT_USER -c $startup
 RETVAL=$?
 echo
}

stop(){
 echo -n $"Stopping Jabot service: " 
 su - $JABOT_USER -c $shutdown 
 RETVAL=$?
 echo
}

status(){
 numproc=`ps -ef | grep jabot.rar | grep -v "grep jabot.rar" | wc -l`
 if [ $numproc -gt 0 ]; then
  echo "Jabot is running..."
  else
  echo "Jabot is stopped..."
 fi
}

restart(){
  stop
  start
}


# See how we were called.
case "$1" in
start)
 start
 ;;
stop)
 stop
 ;;
status)
 status
 ;; 
restart)
 restart
 ;;
*)
 echo $"Usage: $0 {start|stop|status|restart}"
 exit 1
esac

exit 0
