#! /bin/bash
### BEGIN INIT INFO
# Provides:          jenkins
# Required-Start:    $local_fs $remote_fs $network $syslog $time
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Should-Start:      apache2
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Jenkins init script.
# Description:       Init script for Jenkins, a Continuous Integration server.
### END INIT INFO

#
# jenkins    Start/Stop the Jenkins Continuous Integration server.
#
# chkconfig: 345 91 10
# description: Jenkins is a Continuous Integration server. \
# processname: jenkins
# pidfile: /var/run/jenkins.pid


# Source function library.
. /lib/lsb/init-functions

# Check that networking is up.
# [ "${NETWORKING}" = "no" ] && exit 0

JENKINS_USER=jogamp_ci
JENKINS_HOME=/srv/jenkins
startup=$JENKINS_HOME/scripts/start.jenkins.sh
shutdown=$JENKINS_HOME/scripts/stop.jenkins.sh

start(){
 echo -n $"Starting Jenkins service: "
 su - $JENKINS_USER -c $startup
 RETVAL=$?
 echo
}

stop(){
 echo -n $"Stopping Jenkins service: " 
 su - $JENKINS_USER -c $shutdown 
 RETVAL=$?
 echo
}

status(){
 numproc=`ps -ef | grep jenkins.war | grep -v "grep jenkins.war" | wc -l`
 if [ $numproc -gt 0 ]; then
  echo "Jenkins is running..."
  else
  echo "Jenkins is stopped..."
 fi
}

restart(){
  stop
  start
}


# See how we were called.
case "$1" in
start)
 start
 ;;
stop)
 stop
 ;;
status)
 status
 ;; 
restart)
 restart
 ;;
*)
 echo $"Usage: $0 {start|stop|status|restart}"
 exit 1
esac

exit 0
